### ISSUE TITLE
criticalmaas ingest fix

### ISSUE THREAD

**Issue by iross** [UW-Madison-DSI/ask-xDD#109]
The scoping issue I introduced in the dupe checking (fixed in https://github.com/UW-Madison-DSI/ask-xDD/commit/483cab94fa880522fcb5a9773c21aa144a92ad72) labeled some criticalmaas documents with incorrect topic (likely `covid`). We'll need to work through the docids in that set and fix the topic property.

**Comment by JasonLo** [comment]
It has quite a bit of duplications... 

examples: 

Conflicts: paper_id 57873050cf58f17b1550ee34 has climate_change and dolomites
Conflicts: paper_id 5bfac748cf58f129749d3445 has covid-19 and climate_change
Conflicts: paper_id 57a0b1d5cf58f18ca6b05e23 has dolomites and climate_change
Conflicts: paper_id 609b88cd3f2ac7e70117e2e5 has climate_change and covid-19
Conflicts: paper_id 5c6d3ab41faed65548968500 has climate_change and covid-19
Conflicts: paper_id 5d83d0890b45c76cafa8ba77 has dolomites and climate_change
Conflicts: paper_id 5d83d0890b45c76cafa8ba77 has dolomites and climate_change
Conflicts: paper_id 557bebc8e138239225f86616 has dolomites and climate_change
Conflicts: paper_id 57a0b1b6cf58f18ca6b05de4 has climate_change and dolomites
Conflicts: paper_id 57a0b26ccf58f18ca6b05fed has dolomites and climate_change
Conflicts: paper_id 616acf5567467f7269c44608 has covid-19 and climate_change
Conflicts: paper_id 57c91585cf58f17c387a82c5 has climate_change and dolomites
Conflicts: paper_id 5da293c6998e17af82536556 has dolomites and climate_change
Conflicts: paper_id 5da293c6998e17af82536556 has dolomites and climate_change
Conflicts: paper_id 62333a522688b7113580fb6a has climate_change and covid-19
Conflicts: paper_id 607f19bd3f2ac7e701c1eec4 has climate_change and covid-19
Conflicts: paper_id 558de153e13823109f3edffd has dolomites and climate_change
Conflicts: paper_id 5d4e1ee20b45c76cafa434c3 has climate_change and dolomites
Conflicts: paper_id 5d3cade80b45c76cafa1853d has covid-19 and climate_change
Conflicts: paper_id 558ed52ee13823109f3ee5df has climate_change and dolomites
Conflicts: paper_id 57c91585cf58f17c387a82c5 has climate_change and dolomites
Conflicts: paper_id 5643ba87cf58f10f8b3675ea has dolomites and climate_change
Conflicts: paper_id 5643bc04cf58f10f8b3675fa has climate_change and dolomites
Conflicts: paper_id 55b7c46ae13823bd29ba837a has dolomites and climate_change
Conflicts: paper_id 57a0b323cf58f18ca6b0617c has dolomites and climate_change

Before cleaning, let make a plan...

Steps:
1. Deduplicate Weaviate record at paragraph level, so that no records has identical `text_content`
2. Obtain id to topics directly from xdd database
3. Create a temporary new field in Weaviate to store list-like topic. Say `topic_list`
4. Update `topic_list` in all record based on (2)

What do you think @iross

**Comment by JasonLo** [comment]
> Why do you say this is a temporary field? Wouldn't this be the permanent new field that we use for topic filtering (https://github.com/UW-Madison-DSI/ask-xDD/issues/108)?

I was thinking about keeping the old `topic` and replace it with `topic_list` later, just to be clean... perhaps can overwrite `topic` instead, but it will break prod demo.

I had dump the current id to topics from Weaviate for now, but I will need your input on (2) Obtain id to topics directly from xdd database.

**Comment by JasonLo** [comment]
Created ingest_v2 in a949699ef29a9e18a35b0d21d9d1bbfb92d20db5
